# Generated by Django 4.2.15 on 2024-09-23 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_teacherreport_main_indicator'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorSum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_plan_2022_2023', models.FloatField(default=0)),
                ('total_actual_2023_2024', models.FloatField(default=0)),
                ('total_plan_2024_2025', models.FloatField(default=0)),
                ('main_indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.mainindicator')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
