# Generated by Django 4.2.15 on 2024-09-29 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_indicatorsum'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indicatorsum',
            options={'verbose_name': 'Сумма Индикатора', 'verbose_name_plural': 'Сумма Индикаторов'},
        ),
        migrations.AddField(
            model_name='mainindicator',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
