# Generated by Django 4.2.15 on 2024-10-30 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_direction_alter_mainindicator_teacher_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coauthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Окончательный балл для автора')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_indicators', to=settings.AUTH_USER_MODEL)),
                ('coauthors', models.ManyToManyField(blank=True, related_name='coauthored_indicators', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterModelOptions(
            name='direction',
            options={'verbose_name': 'Направление', 'verbose_name_plural': 'Направление '},
        ),
        migrations.AddField(
            model_name='direction',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Процент за публикации'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Баллы'),
        ),
        migrations.AddField(
            model_name='mainindicator',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Базовый балл'),
        ),
        migrations.CreateModel(
            name='CoauthorScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Баллы')),
                ('coauthor_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coauthor_scores', to='main.coauthor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='coauthor',
            name='indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.indicator'),
        ),
    ]
