# Generated by Django 4.2.15 on 2024-10-30 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='articles/files/'),
        ),
    ]
