# Generated by Django 4.2.15 on 2024-11-04 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_article_comments_article_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='points',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
