# Generated by Django 4.2.15 on 2024-11-04 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_article_deadline_article_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
