# Generated by Django 4.2.15 on 2024-11-10 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_article_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='start',
            field=models.DateField(blank=True, null=True, verbose_name='Начало: '),
        ),
        migrations.AlterField(
            model_name='article',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Конец: '),
        ),
    ]
